# Generated by Django 5.0.dev20230123050841 on 2023-01-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_event_date_event_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="painting1.JPG", upload_to=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
