# Generated by Django 5.0.dev20230123050841 on 2023-01-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_user_avatar_alter_event_created_alter_event_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="painting2.png", upload_to=""),
        ),
    ]
