# Generated by Django 5.0.dev20230123050841 on 2023-01-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="painting2.png", upload_to="images/"),
        ),
    ]
